blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/rsteckler/axiocnc/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://axiocnc.com/docs
    about: Check the documentation for answers
