#!/bin/sh
set -e
TMPFILE=$(mktemp)
trap "rm -f $TMPFILE" EXIT
curl -L https://github.com/rsteckler/AxioCNC/releases/download/v0.0.89/axiocnc-headless_0.0.89_armhf.deb -o "$TMPFILE"
sudo dpkg -i "$TMPFILE"
